<?php

return [
    [
        "name" => "Arcanis l'Onnipotente",
        "mana_cost" => 3,
        "mana_type" => "fire",
        "thumb" => "https://images.ctfassets.net/s5n2t79q9icq/4s3ygGWPG5QRL2SDOMZ3HA/51d9e0188b4578dff5aab889bf846e57/en_articles_archive_card-image-gallery_strixhaven-school-mages-art-cards-2021-04-15-meta-image.jpeg",
        "type" => "Creatura Leggendaria - Mago",
        "edition" => "X",
        "first_effect" => "pesca 3 carte",
        "second_effect" => "Fai tornare Arcanis l'Onnipotente in mano al suo proprietario.",
        "third_effect" => "Effetto 3",
        "fourth_effect" => "",
        "description" => "Non preoccuparti della mia origine, della mia razza o del mio lignaggio. Chiedi i miei risultati nell'arena e poi fai la tua scommessa",
        "strength" => 3,
        "constitution" => 4,
    ],
    [
        "name" => "Gianmaria S. il durevole",
        "mana_cost" => 4,
        "mana_type" => "water",
        "thumb" => "http://ninjacrunch.com/wp-content/uploads/2011/07/p3/4.jpg",
        "type" => "Creatura Leggendaria - Guerriero",
        "edition" => "X",
        "first_effect" => "tappa 2 carte",
        "second_effect" => "blocca un attacco anche da tappato.",
        "third_effect" => "",
        "fourth_effect" => "",
        "description" => "Si sa poco di questo Guerriero leggendario. Il significato della S. nel suo nome è perso nei tempi. molti sostengono che il suo soprannome sia un dono della sua moglie.",
        "strength" => 2,
        "constitution" => 8,
    ],
    [
        "name" => "Antonio lo sconnessionato",
        "mana_cost" => 2,
        "mana_type" => "nature",
        "thumb" => "https://assets.dicebreaker.com/mtg-modern-horizons-2-artwork.png/BROK/resize/1200x1200%3E/format/jpg/quality/70/mtg-modern-horizons-2-artwork.png",
        "type" => "Creatura Leggendaria - Arciere",
        "edition" => "X",
        "first_effect" => "tappa per spaccare una creatura al prossimo turno",
        "second_effect" => "i danni ricevuti vengono calcolati il turno dopo.",
        "third_effect" => "",
        "fourth_effect" => "",
        "description" => "Tutti quelli che lo hanno avvicinato hanno sperimentato un rallento dei movimenti che gli hanno impedito di potersi difendere dai suoi attacchi imprevedibili.",
        "strength" => 6,
        "constitution" => 2,
    ],
];
